from pydantic import BaseModel

REPORT_DISCLAIMER = (
    "This report is restricted to school leadership and contains identifiable "
    "student information (the Student Cases section). The trend/management "
    "narrative is AI-assisted and aggregate; the case list is not. Handle, "
    "store, and share this document in compliance with the Personal Data "
    "Protection Act 2010 (PDPA). Individual student matters must still follow "
    "established counseling protocols."
)


class ClassRiskSummary(BaseModel):
    class_name: str
    total_students: int
    low_risk: int
    moderate_risk: int
    high_risk: int


class StudentCase(BaseModel):
    """A single student behind this period's KPI counts — populated directly
    from the DB (never sent to or generated by the AI), since leadership
    needs the actual, current case list, not an LLM's paraphrase of it."""

    student_id: str
    name: str
    class_name: str
    risk_level: str | None = None
    intervention_status: str | None = None
    referral_status: str | None = None


class MonthlyKPI(BaseModel):
    period: str
    total_students: int
    low_risk_count: int
    moderate_risk_count: int
    high_risk_count: int
    active_interventions: int
    referrals_made: int
    referrals_acknowledged: int
    counseling_sessions: int


class DashboardReport(BaseModel):
    generated_at: str
    period: str
    school_kpis: MonthlyKPI
    class_breakdown: list[ClassRiskSummary]
    # None when the AI narrative hasn't been generated yet for this
    # period/language — KPIs are always live, but Agent 4 only runs when
    # explicitly requested (see POST /reports/dashboard/narrative), never
    # just because the dashboard is being displayed.
    trend_analysis: str | None = None
    management_summary: str | None = None
    recommendations: list[str] | None = None
    disclaimer: str = REPORT_DISCLAIMER


class DashboardNarrative(BaseModel):
    trend_analysis: str
    management_summary: str
    recommendations: list[str]
